---
name: Securin Scan
"on":
- workflow_dispatch
- pull_request
jobs:
  scanning:
    env:
      APP_ID: f2bfcb726b45a3d6e7285c5684d1aa197c3a7aa1c6cc392e20178175a64f9692
      REQ_URL_MAP: "${{toJSON('{\"SL_RESULTPARSER_API_HOST\":\"http://09c6-116-72-121-77.ngrok.io/resultparserapi/v1\"\
        ,\"SL_API_HOST\":\"http://653b-116-72-121-77.ngrok.io/shiftleftapi\",\"SL_RESULT_API_HOST\"\
        :\"http://247a-116-72-121-77.ngrok.io/resultapi/v1\"}')}}"
    steps:
    - name: Access token
      id: access_token
      run: "tkn=$( curl --request POST 'http://09c6-116-72-121-77.ngrok.io/resultparserapi/v1/access_token'\
        \  --header 'Content-Type: application/json'  --data-raw  '{\"userId\": \"\
        ${{ secrets.USER_NAME }}\", \"password\": \"${{ secrets.PASSWORD }}\" }' --data-raw\
        \ ' ' )\necho \"::set-output name=token::$tkn\""
    - name: Retrieve Scan Info
      id: auth_token
      run: "respJson=$(curl --location --request GET 'http://653b-116-72-121-77.ngrok.io/shiftleftapi/scan-info?app_id=${{\
        \ env.APP_ID }}'  --header 'Authorization: Bearer ${{fromJson(steps.access_token.outputs.token).access_token}}'\
        \  --data-raw ' ' )\necho \"::set-output name=authTokenJson::$respJson\""
    - uses: actions/checkout@v2
    - name: Scan Initiated
      id: sec_scan_init
      run: "docker login --username  ${{fromJson(steps.auth_token.outputs.authTokenJson).user}}\
        \ --password ${{fromJson(steps.auth_token.outputs.authTokenJson).password}}\
        \ ${{fromJson(steps.auth_token.outputs.authTokenJson).proxyUrl}}\ndocker pull\
        \ -q ${{fromJson(steps.auth_token.outputs.authTokenJson).imageTag}}\ndocker\
        \ run -v ${{github.workspace}}:/src  --volume ${{github.workspace}}:/workdir\
        \  ${{fromJson(steps.auth_token.outputs.authTokenJson).imageTag}} -access_tkn\
        \ ${{fromJson(steps.access_token.outputs.token).access_token}} -app_id ${{\
        \ env.APP_ID }} -req_url_map ${{ env.REQ_URL_MAP }} event:${{ github.event_name\
        \ }}  pr_number:${{ github.event.number }}"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: "${{github.workspace}}/results/result.sarif"
      if: hashFiles('**/result.sarif') !=''
    - name: Evaluate build status
      run: "cat ${{github.workspace}}/results/status.txt\nexit 1\n"
      if: hashFiles('**/status.txt') !=''
    runs-on: ubuntu-latest
